# Generated by Django 4.2.3 on 2023-08-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.CharField(max_length=3)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('feedback', models.PositiveIntegerField()),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
    ]
